### ISSUE TITLE
Support for Conditional Requests

### ISSUE THREAD

**Issue by rockwotj** [oscardelben/firebase-ruby#77]
The Realtime Database just added support for conditional requests (AKA transactions) via the REST API. It'd be great if firebase-ruby supported that.

The docs for this are here: https://firebase.google.com/docs/reference/rest/database/#section-conditional-requests

/cc @caseycrogers

**Comment by vincentwoo** [comment]
This is a great idea, hopefully we can get to it. If you can make a PR that would be great too!

**Comment by rockwotj** [comment]
I sadly don't have time, I but maybe someone can come by and add support!

**Comment by caseycrogers** [comment]
I own the feature so I can see if I get the time to put a pr together!

On Jul 30, 2017 3:42 PM, "Tyler Rockwood" <notifications@github.com> wrote:

I sadly don't have time, I but maybe someone can come by and add support!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oscardelben/firebase-ruby/issues/77#issuecomment-318935151>,
or mute the thread

**Comment by voidviking** [comment]
@oscardelben with the recent commit, is there any documentation provided for conditional query?

**Comment by vincentwoo** [comment]
This feature has not been built yet
